#!/usr/bin/env php
<?php

// silex core
require_once __DIR__.'/vendor/autoload.php';

// common config 
require_once __DIR__.'/config/common.php';

// environement config (DBs ...)
require_once __DIR__.'/config/' . 'local' . '.php';

// init app
require_once __DIR__.'/src/app.php';

$console = new Symfony\Component\Console\Application();
$console->add(new Console\Sample());

$console->run();